[package]
name = "fssh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.93"
crossterm = "0.28.1"
nom = "7.1.3"
ratatui = "0.29.0"
shellexpand = "3.1.0"
